#What is a String in Python?
#A string is a sequence of characters (letters, numbers, symbols, spaces) enclosed
#within single quotes ('), double quotes ("), or triple quotes (''' / """).

#STRING METHODS:
#String methods are built-in functions for strings that help in performing operations like searching
#modifying, splitting, and formatting text.

#EX:
text = "hello"
print(text.upper()) 
A="python programming"
print(A.title())
B ="HELLO"
print(B.lower())
C ="hello"
print(C.strip())
text = "I like Java"
print(text.replace("Java", "Python")) 

  